CI: Reworks engine logic

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -37,10 +37,13 @@ install:
   - |
     if [ $PROG == "RDKIT" ]; then
       conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/rdkit.yaml
-    elif [ $PROG == "PSI_V11" ]; then
+    elif [ $PROG == "PSI4_V11" ]; then
       conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/psi_v11.yaml
-    else
+    elif [ $PROG == "PSI4" ]; then
       conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/psi.yaml
+    else
+      echo "ERROR: No match for PROG ($PROG)."
+      exit 1
     fi
   - source activate test
 
